### ISSUE TITLE
Cluster super slow loading spack on startup??

### ISSUE THREAD

**Issue by steven-basart** [centerforaisafety/cerberus-cluster#58]
````
ssh test_oci_2                                                                                                                                                                            ░▒▓ ✔  19:21:54 

⠀⠀⠀⠀⢀⡤⢂⣴⠾⠛⠷⢶⣤⡀⠀⠀⠀
⠀⠀⠀⣴⠟⣁⣉⣁⣀⡀⠈⢶⡌⠻⢦⠀⠀
⠀⠀⣸⡏⠜⠋⣩⡭⠉⠛⢷⢸⡇⠸⣦⡁⠀
⠀⠀⢿⡄⠀⢰⡟⠀⠀⠀⠀⣼⠇⠀⠘⣷⠀
⠀⠀⢈⠻⡆⢸⡇⢷⣤⣀⣚⣋⣠⡔⣸⡏⠀
⠀⠀⠀⠳⣦⡘⠷⡀⠈⠉⢉⣉⢉⣴⠟⠀⠀
⠀⠀⠀⠀⠈⠛⠷⢶⣤⡶⠟⠡⠚⠁⠀⠀⠀

Welcome to the Center for AI Safety Compute Cluster!

We're using costly data storage for the moment. If you can try to self limit how much you use we'd appreciate it.

The compute cluster is exclusively designated for work on pre-approved safety projects. Do not use it for any unapproved projects.

Last login: Mon Apr 24 23:21:29 2023 from c-73-139-146-86.hsd1.fl.comcast.net

^CTraceback (most recent call last):
  File "/nfs/cluster/spack/bin/spack", line 54, in <module>
    sys.exit(main())
  File "/nfs/cluster/spack/lib/spack/spack_installable/main.py", line 35, in main
    import spack.main  # noqa: E402
  File "/nfs/cluster/spack/lib/spack/spack/main.py", line 36, in <module>
    import spack.cmd
  File "/nfs/cluster/spack/lib/spack/spack/cmd/__init__.py", line 26, in <module>
    import spack.environment as ev
  File "/nfs/cluster/spack/lib/spack/spack/environment/__init__.py", line 332, in <module>
    from .environment import (
  File "/nfs/cluster/spack/lib/spack/spack/environment/environment.py", line 40, in <module>
    import spack.user_environment as uenv
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 951, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 894, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1157, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1129, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1241, in find_spec
  File "<frozen importlib._bootstrap_external>", line 82, in _path_stat
KeyboardInterrupt

```

**Comment by steven-basart** [comment]
I think we need to delete or comment this out: sudo vim /etc/profile.d/spack.sh

**Comment by andriy-safe-ai** [comment]
Slow loading was related to NFS deployment. Closing.

**Comment by andriy-safe-ai** [comment]
Closing. New cluster will be deployed without spack.
